/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/Button.vue')['default']
    FormGroup: typeof import('./../components/FormGroup.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Status: typeof import('./../components/Status.vue')['default']
    Tags: typeof import('./../components/Tags.vue')['default']
  }
}
